- Numpy is a pacakage used to math operations
- Numpy means Numerical Python
- Because of Numpy we can create multi dimensional data
- Data represent in form of lists or tuple
- same as Data represent in mutiple ways
    - **List** : Doesn't have any dimensions
    - **Arrays** : has dimensions created by Numpy, mostly used in ML
    - **Tesnors** : has dimensions also vecto representation created by Tensorflow in DL NLP AI
    - **Torch** : also another form of vectors created by Torch in DL NLP AI

In [4]:
[1,2,3,4]
array([1,2,3,4]) # CPU support but not GPU
tensor([1,2,3,4]) # CPU and GPU support will see this usage in future

NameError: name 'array' is not defined

In [3]:
import numpy as np

In [12]:
np.__version__

'1.26.4'

In [ ]:
#Note: Numpy is very powerful module
# The version are impact on another module
# some times we might upgrade the version or downgrade the version

In [5]:
list1=[1,2,3,4]
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4])

In [7]:
type(arr1)

numpy.ndarray

In [18]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [9]:
l1=[1,2,3]
l2=[10,20,30]
np.array(l1)

array([1, 2, 3])

In [22]:
np.array(l1,l2)

TypeError: Field elements must be 2- or 3-tuples, got '10'

In [11]:
np.array([l1,l2])

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
# if there are multiple lists , then under array they should be as list don't 

In [26]:
l1=[1,2,3]
l2=[10,20,30]
np.array(l1) # working
np.array(l1,l2) # won't work
np.array([l1,l2]) # working

In [15]:
arr1 = np.array([1,2,3])
print(type(arr1))
print(arr1.ndim)

<class 'numpy.ndarray'>
1


In [30]:
arr2 =  np.array([[1,2,3],[10,20,30]])
arr2.ndim

2

In [27]:
l1=[1,2,3]
l2=[10,20,30]
arrt2 = np.array((l1,l2))

In [29]:
arrt2.ndim

2

In [31]:
arr3 =  np.array([[[1,2,3],[10,20,30]]])
arr3.ndim

3

In [39]:
np.array([[[[10,20]]]]).ndim

4

In [ ]:
arr1 # 1d

In [57]:
arr1 =np.array([1,2,3,4,5])

In [63]:
#arr2 #2d
arr2 = np.array([[1,2,3,4,5],[10,11,12,13,14]])

In [77]:
arr3 = np.array([[[1,2,3],[10,20,30]]])

- 1D : Only one layer of values only one axis (x)
- 2D : Two axis of values (x,y)
- 3D : Thress axis of values (x,y,z)
-  

In [59]:
arr1.shape

(5,)

In [65]:
arr2.shape

(2, 5)

In [79]:
arr3.shape

(1, 2, 3)

**interpretation of shape (1,2,3)***
- It is a 3-D data
- 2 rows and 3 columns
- we have 1 matrix available with the shape (2,3)

**interpretation of shape (2,2,3)***
- It is a 3-D data
- 2 rows and 3 columns
- we have 2 matrix available with the shape (2,3)

In [87]:
arr4 = np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])
arr4.shape

(2, 2, 3)

In [91]:
#(1,2,3,4)
arr5= np.array([[[[1,2,3,5],[6,7,8,9],[10,11,12,13]],[[14,15,16,17],[18,19,20,30],[31,32,33,34]]]])
arr5.shape

(1, 2, 3, 4)

In [99]:
l1=[1,2,3,4]
l2=[10,20,30,40]
l3=[100,200,300,400]
L1 =[l1,l2,l3] # 3*4
L2 =[l1,l2,l3] # 3*4
np.array([[L1,L2]]).shape

(1, 2, 3, 4)

In [101]:
np.array([L1,L2]).shape

(2, 3, 4)