In [52]:
l1=[1,2,3]
l2=[10,20,30]
#l3=[11,22,33]
l3=[i+j for i,j in zip(l1,l2)]
l3

[11, 22, 33]

In [54]:
import numpy as np
arr1= np.array(l1)
arr2= np.array(l2)
arr1+arr2

array([11, 22, 33])

- Element wise operations works in Numpy

**how to convert array to list**

In [11]:
arr1

array([1, 2, 3])

In [13]:
list(arr1) #type casting

[1, 2, 3]

In [15]:
arr1.tolist()

[1, 2, 3]

**Speed Analysis**

In [ ]:
# take a two lists of 100 no's
# multiply two list
#calculate time process


# take a two lists of 100 no's
# multiply two list
#calculate time process

In [18]:
import time
l1=range(1,1000000)
l2=range(1,1000000)
start=time.time()
[i*j for i,j in zip(l1,l2)]
end=time.time()
print(f'Time taken is : {end-start}')


Time taken is : 0.2823364734649658


In [20]:
range(3)

range(0, 3)

In [24]:
list(range(0,3))

[0, 1, 2]

In [30]:
import numpy as np
np.arange(3)

array([0, 1, 2])

In [36]:
import time
arr1=np.arange(1000000)
arr2=np.arange(1000000)
start=time.time()
arr3= arr1*arr2
end=time.time()
print(f'Time taken is : {end-start}')

Time taken is : 0.004084587097167969


In [46]:
np.mean([1,2,3,4,5,100])

19.166666666666668

In [44]:
np.median([1,2,3,4,5,100])

3.5

In [48]:
-min
-max
-sum
-count
-mean
-median
-mode
-variance
-standard deviation
-covariance
-correlation
-percentile
-Quantile

AttributeError: module 'numpy' has no attribute 'mode'